# Generated by Django 5.2.17 on 2026-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingSMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=30)),
                ("message_text", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                ("network", models.CharField(blank=True, max_length=100)),
                (
                    "language_code",
                    models.CharField(
                        blank=True,
                        help_text="Conversation language snapshot at receipt time.",
                        max_length=10,
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Incoming SMS",
                "verbose_name_plural": "Incoming SMS",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SmsDeliveryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Africa's Talking messageId, when provided.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("status_code", models.CharField(blank=True, max_length=20)),
                ("failure_reason", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "fingerprint",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS delivery report",
                "verbose_name_plural": "SMS delivery reports",
                "ordering": ("-updated_at",),
            },
        ),
    ]
