# Generated by Django 5.2.17 on 2026-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_incomingsms_smsdeliveryreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingsms",
            name="reply_text",
            field=models.TextField(
                blank=True, help_text="What MANYA replied, in the user's language."
            ),
        ),
    ]
