# Generated by Django 5.2.17 on 2026-08-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal category",
                "verbose_name_plural": "Legal categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LegalSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CONSTITUTION", "Constitution"),
                            ("ACT", "Act of Parliament"),
                            ("AMENDMENT_ACT", "Amendment Act"),
                            ("STATUTORY_INSTRUMENT", "Statutory Instrument"),
                            ("REGULATION", "Regulation"),
                            ("LEGAL_NOTICE", "Legal Notice"),
                            ("GAZETTE", "Government Gazette"),
                            ("COURT_DECISION", "Court decision"),
                            ("GOVERNMENT_POLICY", "Government policy"),
                            ("GOVERNMENT_GUIDELINE", "Government guideline"),
                            ("ULRC_PUBLICATION", "ULRC publication"),
                            ("ULII", "ULII"),
                            ("OTHER_VERIFIED", "Other verified source"),
                        ],
                        default="ACT",
                        max_length=40,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("document_title", models.CharField(blank=True, max_length=255)),
                ("document_identifier", models.CharField(blank=True, max_length=255)),
                ("chapter", models.CharField(blank=True, max_length=100)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("jurisdiction", models.CharField(default="UG", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("AMENDED", "Amended"),
                            ("REPEALED", "Repealed"),
                            ("SUPERSEDED", "Superseded"),
                            ("UNCOMMENCED", "Not yet commenced"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "authority_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (
                                1,
                                "Level 1 — Constitution, Acts, Regulations, Official decisions",
                            ),
                            (
                                2,
                                "Level 2 — ULII, recognised legal institutes / legal-aid bodies",
                            ),
                            (
                                3,
                                "Level 3 — NGOs, universities, research & educational resources",
                            ),
                            (
                                4,
                                "Level 4 — Never legal authority (blogs, social media, random sites)",
                            ),
                        ],
                        default=1,
                    ),
                ),
                ("is_authoritative", models.BooleanField(default=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal source",
                "verbose_name_plural": "Legal sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LegalTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="legal.legalcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal topic",
                "verbose_name_plural": "Legal topics",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LegalContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("rights_information", models.TextField(blank=True)),
                ("what_this_means", models.TextField(blank=True)),
                ("next_steps", models.TextField(blank=True)),
                ("documents_required", models.TextField(blank=True)),
                ("source_title", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("legal_reference", models.CharField(blank=True, max_length=255)),
                ("section_reference", models.CharField(blank=True, max_length=255)),
                ("last_verified", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REVIEW", "Review"),
                            ("VERIFIED", "Verified"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "disclaimer",
                    models.TextField(
                        default="This information is provided for general legal and policy awareness. MANYA is not a law firm and this information does not constitute legal advice. Laws and policies may change. Always consult the original source or a qualified legal professional for advice about your specific situation."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_contents",
                        to="languages.language",
                    ),
                ),
                (
                    "original_content",
                    models.ForeignKey(
                        blank=True,
                        help_text="For translations: the source content this record was translated from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations",
                        to="legal.legalcontent",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contents",
                        to="legal.legalsource",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="legal.legaltopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal content",
                "verbose_name_plural": "Legal content",
                "ordering": ["topic__display_order", "language__code"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("verification_status", "ARCHIVED"), _negated=True
                        ),
                        fields=("topic", "language"),
                        name="legalcontent_unique_active_topic_language",
                    )
                ],
            },
        ),
    ]
