# Generated by Django 5.2.17 on 2026-08-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "field",
                    models.CharField(
                        help_text="Database field being translated, e.g. name, rights_information.",
                        max_length=100,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Only verified translations should be shown publicly.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manya_translations",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_translations",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content translation",
                "verbose_name_plural": "Content translations",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "language", "field"],
                        name="languages_c_content_791d3e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "content_type", "object_id", "field"),
                        name="unique_content_translation",
                    )
                ],
            },
        ),
    ]
