# Generated by Django 5.2.17 on 2026-08-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0002_contenttranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenttranslation",
            name="translation_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("sunbird", "Sunbird"),
                    ("system", "System"),
                ],
                default="manual",
                help_text="Where this translation came from (Sunbird, admin, system).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contenttranslation",
            name="translation_status",
            field=models.CharField(
                choices=[
                    ("machine_translated", "Machine translated"),
                    ("reviewed", "Reviewed"),
                ],
                default="machine_translated",
                help_text="Machine translations must be reviewed by a human before they should be treated as authoritative.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_text", models.TextField()),
                ("source_language", models.CharField(max_length=10)),
                ("target_language", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Translation cache",
                "verbose_name_plural": "Translation cache",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_hash", "source_language", "target_language"),
                        name="translation_cache_unique",
                    )
                ],
            },
        ),
    ]
