# Generated by Django 5.2.17 on 2026-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("languages", "0003_contenttranslation_translation_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="content_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
