# Generated by Django 5.2.17 on 2026-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("last_verified", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Policy update",
                "verbose_name_plural": "Policy updates",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
