# Generated by Django 5.2.17 on 2026-08-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UssdSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("language_code", models.CharField(default="en", max_length=10)),
                ("menu", models.CharField(blank=True, max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "USSD session",
                "verbose_name_plural": "USSD sessions",
                "ordering": ("-updated_at",),
            },
        ),
    ]
