# Generated by Django 5.2.17 on 2026-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ussd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ussdsession",
            name="channel",
            field=models.CharField(
                choices=[("ussd", "USSD"), ("sms", "SMS")],
                default="ussd",
                help_text="Which channel created this conversation.",
                max_length=10,
            ),
        ),
    ]
