# Generated by Django 5.2.17 on 2026-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ussd", "0002_ussdsession_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ussdsession",
            name="channel",
            field=models.CharField(
                choices=[("ussd", "USSD"), ("sms", "SMS"), ("voice", "Voice")],
                default="ussd",
                help_text="Which channel created this conversation.",
                max_length=10,
            ),
        ),
    ]
